server:
  port: 8081

spring:
  application:
    name: eu-file
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml

minio:
  endpoint: http://192.168.1.57:9000
  username: minioadmin
  password: minioadmin
  bucket-name: eucloud
